### PR TITLE
Two german basemaps and a german version of the Khartis UI

### PR DESCRIPTION
**Pull request by mukil**
This pull requests covers the following changes to the Khartis source code (closing #5):

- German translation of the Khartis UI
- Adding a basic (1) `german states 2016` topojson basemap plus a corresponding dictionary
The dictionary for this map contains two identifiers `RS` (and `RS_0` just a different notation for `RS`) and `NUTS_1`, plus (yet only) the german place name. This dictionary was compiled by hand.
- Adding a basic (2) `german districts 2016` topojson basemap plus a corresponding dictionary
The dictionary for this map contains three identifiers `RS` (acronym for "Regionalschlüssel"), `NUTS3`, plus (yet only) the german place name. Sources for this dictionary are [NUTS Classification, at RAMON - Reference And Management Of Nomenclatures](http://ec.europa.eu/eurostat/ramon/nomenclatures/index.cfm?TargetUrl=LST_CLS_DLD&StrNom=NUTS_2013L&StrLanguageCode=EN&StrLayoutCode=HIERARCHIC#) and [DeStatis Gemeindeverzichnis](https://www.destatis.de/DE/ZahlenFakten/LaenderRegionen/Regionales/Gemeindeverzeichnis/Administrativ/Archiv/GVAuszugJ/31122015_Auszug_GV.html).
- Added an example dataset for basemap (2) containing open data population stats with NUTS3 level IDs

Datasource for the basemap (2) has been the administrative dataset "Verwaltungsgebiete 1: 2 500 000, Stand 01.01.2016" from [BKG Open Data](http://www.geodatenzentrum.de/geodaten/gdz_rahmen.gdz_div?gdz_spr=deu&gdz_akt_zeile=5&gdz_anz_zeile=0&gdz_unt_zeile=0&gdz_user_id=0). Source for the example dataset is [Kreisfreie Städte und Landkreise nach Fläche, Bevölkerung und Bevölkerungsdichte am 31.12.2015](https://www.destatis.de/DE/ZahlenFakten/LaenderRegionen/Regionales/Gemeindeverzeichnis/Administrativ/Aktuell/04Kreise.html). Both basemaps contain only three layers, namely `poly`, `centroid` and `line`. The points on the centroid layer were revised manually using QGis (which was inevitable to get any useful result). The basemaps therefore (yet) do lack the layers `line-up` and `poly-down` but I also do not know (yet) for what these layers are required (see [How to create a basemap for Khartis](/AtelierCartographie/Khartis/wiki/How-to-create-a-basemap-for-Khartis)).

Before building a Khartis distribution now we should agree on a way to include the metadata (attribution, license) information for the basemap in exports. The configuration of the two new basemaps but also the configuration of the example dataset do now each include two additional properties: `attribution` and `license`.

If I can or need to correct anything before the merge, please do not hesitate to drop me a line here. I would be happy If we can find a quick fix for the issue i just described in #8 before we merge.

Cheers!

### CODE REVIEW

**Comment by TomBor** [comment]
Thank you @mukil for your great contribution.

On the metadata part, although we agree of the need of such information. We cannot add it, no development is schedule for the time being. But we keep your idea for sure!

Before to merge @apezel will verify your PR.

**Comment by mukil** [comment]
Hey @Tombor, thanks for letting me know. I am sorry that I could not make that clear before but including the proper attribution for the german basemap in all Khartis exports automatically is a strict requirement for this basemap contribution. If we really don't have a solution for the moment I must close this PR / or herewith ask you to not merge it before #6 is resolved.

**Comment by TomBor** [comment]
Hi @mukil ,
@apezel add an attribution line that solve #6. Is it ok for you now?

**Comment by mukil** [comment]
Thanks a lot @apezel! From my point of view the solution is fine now. So, yes!
I might be able to add another example over the course of today but after that, feel free to go ahead!

Thanks a lot for all your help on getting this done!

**Comment by mukil** [comment]
This is it. I think these are all german basemap changes and ready to merge.

**Comment by apezel** [comment]
@mukil @TomBor @boogheta I merged this pull request. There was a problem in the file environment.js with ```d3.geo.conicConformal() -> d3.geoConicConformal()```. I corrected this in my last commit. Can you please pull the latest commit if you plan to do changes on your branch ?
By the way, the map Deutschland > Landkreise (2016) seems pretty big (~400ko). Maybe it could be optimized.
Thank for your great work on Khartis.

**Comment by boogheta** [comment]
No issues here with the environment.js file, it still followed through, preprod is up to date. I'll be waiting for @tombor's approval before pulling in production.
Thanks a lot @mukil & @apezel

**Comment by TomBor** [comment]
Thank you again @mukil for the quality of your work. On the landkreise basemap, I made two small changes: delete unused attributes in geometry to only keep "RS" and add länder limits.
We are good for production!

**Pull request merged**
