### PR TITLE
Translated user interface elements and in-app descriptions into german language

### PR DESCRIPTION
**Pull request by mukil**
Hi, i was already in contact with Thomas and he suggested to open up a PR here.

Here is an outline of all the changes I made in the two commits:
- Thoroughly translated all visible labels in the Khartis UI to german
- Translated all the map names in the select menu available in "Step 1"
- Translated the names of the currently available examples
- Translated some of the short explanatory texts as well
- Added short descriptions to 4 projections

I would be happy if someone could check if I missed to translate some parts of the application i do not know yet or if i can do anything to improve the translation.

Thanks for the great work & Cheers!

### CODE REVIEW

**Comment by mukil** [comment]
I just looked over the two commits and found some terms i am not 100% satisfied with yet. I plan to make the final revision tomorrow.

**Comment by mukil** [comment]
Waiting for #7.

**Comment by boogheta** [comment]
Seems complete now, or are you still thinking of missing elements @apezel?
Thanks a lot @mukil!

**Comment by mukil** [comment]
Great, so, from my perspective the result is OK now. If the UI gets extended please feel free to open up and assign me to any issue concerning the german translation. Over the next six months or so I will be happy to update it before, let's say, any new release.
Cheers!

**Comment by mukil** [comment]
The changes proposed here plus all the latest additions to the UI labels are now part of pull request #9.

**Pull request closed without merging**
